# Generated by Django 2.0.3 on 2018-04-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(help_text='Description', max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Name of category', max_length=30, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of create', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='message',
            field=models.TextField(max_length=4000, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='updated_at',
            field=models.DateTimeField(help_text='The date of update', null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date of create', verbose_name='Create at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(help_text='Message of post', max_length=4000, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Title of post', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(help_text='The date of update', null=True, verbose_name='Update at'),
        ),
    ]
