# Generated by Django 2.0.3 on 2018-04-17 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(help_text='Description', max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Name of category', max_length=30, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='URL string shortcut', max_length=40, verbose_name='Shortcut'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of creation', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='message',
            field=models.TextField(max_length=4000, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to='forum.Post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='updated_at',
            field=models.DateTimeField(help_text='Date of update', null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of creation', verbose_name='Create at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(help_text='Message of post', max_length=4000, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Title of post', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(help_text='Date of update', null=True, verbose_name='Update at'),
        ),
    ]
