# Generated by Django 2.0.3 on 2018-04-19 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20180417_1423'),
        ('forum', '0002_auto_20180416_1916'),
    ]

    operations = [
    ]
