# Generated by Django 2.0.3 on 2018-04-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_merge_20180419_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of creation', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='updated_at',
            field=models.DateTimeField(help_text='Date of update', null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of creation', verbose_name='Create at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(help_text='Date of update', null=True, verbose_name='Update at'),
        ),
    ]
