# Generated by Django 2.0.3 on 2018-04-19 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20180419_0123'),
        ('forum', '0002_auto_20180414_1328'),
    ]

    operations = [
    ]
