# Generated by Django 2.0.3 on 2018-04-24 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0012_auto_20180423_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('required', models.BooleanField(default=False)),
                ('when_needed', models.BooleanField(default=False)),
                ('check', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initialized', models.BooleanField(default=False, editable=False)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('initialized', models.BooleanField(default=False, editable=False)),
                ('careline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careline.Checklist')),
            ],
        ),
        migrations.AddField(
            model_name='checkitem',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careline.Procedure'),
        ),
    ]
