# Generated by Django 2.0.3 on 2018-04-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkitem',
            name='age',
            field=models.CharField(max_length=5),
        ),
    ]
