# Generated by Django 2.0.3 on 2018-04-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careline', '0002_auto_20180424_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
