# Generated by Django 2.0.3 on 2018-04-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careline', '0003_checklist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='slug',
        ),
    ]
