# Generated by Django 2.0.3 on 2018-05-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='motive',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='shift',
        ),
    ]
