# Generated by Django 2.0.3 on 2018-05-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Canceled', 'Canceled')], default='Scheduled', editable=False, help_text='Is this appointment still scheduled?', max_length=20, verbose_name='Status'),
        ),
    ]
