# Generated by Django 2.0.3 on 2018-05-28 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20180524_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], help_text='Preferred day of the week. It is not guaranteed that the appointment will be marked on the preferred day.', max_length=10, verbose_name='Day of the week'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Preferred doctor. It is not guaranteed that the appointment will be scheduled with the doctor preferred.', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='users.HealthTeam', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='shift',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon')], help_text='Preferred shift', max_length=10, verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='speciality',
            field=models.CharField(choices=[('Speech Therapy', 'Speech Therapy'), ('Psychology', 'Psychology'), ('Physiotherapy', 'Physiotherapy'), ('Occupational Therapy', 'Occupational Therapy'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('General Practitioner', 'General Practitioner')], help_text='Desired specialty', max_length=30, verbose_name='Speciality'),
        ),
    ]
