# Generated by Django 2.0.3 on 2018-05-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20180523_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='risk',
            field=models.IntegerField(default=0),
        ),
    ]
