# Generated by Django 2.0.3 on 2018-05-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointmentrequest_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='risk',
            field=models.IntegerField(default=5),
        ),
    ]
