# Generated by Django 2.0.3 on 2018-05-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20180508_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Declined', 'Declined')], default='Pending', editable=False, help_text='Was the request accepted?', max_length=20, verbose_name='Status'),
        ),
    ]
