# Generated by Django 2.0.3 on 2018-05-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20180524_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='risk',
            field=models.IntegerField(choices=[(5, 'Not urgent'), (4, 'Not very urgent'), (3, 'Urgent'), (2, 'Very urgent'), (1, 'Emerging')], default=5, verbose_name='Risk'),
        ),
    ]
