# Generated by Django 2.0.3 on 2018-04-26 13:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='document',
            field=models.FileField(default=datetime.datetime(2018, 4, 26, 13, 15, 15, 194894, tzinfo=utc), upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='day',
            field=models.DateTimeField(auto_now=True, help_text='Patient Care Day', verbose_name='Created at'),
        ),
    ]
