# Generated by Django 2.0.3 on 2018-05-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticdata',
            name='weight',
            field=models.PositiveIntegerField(help_text='In grams', verbose_name='Weight at birth'),
        ),
    ]
