# Generated by Django 2.0.3 on 2018-04-28 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='document',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.HealthTeam', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='day',
            field=models.DateTimeField(auto_now=True, help_text='Patient Care Day', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='message',
            field=models.TextField(help_text='Message of medical records', max_length=4000, verbose_name='Message'),
        ),
    ]
