# Generated by Django 2.0.3 on 2018-04-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0002_auto_20180423_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='day',
            field=models.DateTimeField(auto_now_add=True, help_text='Patient Care Day', verbose_name='Created at'),
        ),
    ]
