# Generated by Django 2.0.3 on 2018-05-07 13:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180507_0027'),
        ('medicalrecords', '0002_auto_20180507_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structured_physical_exam', models.FileField(blank=True, upload_to='media/medicalrecords/specificexams', verbose_name='Structured Physical Exam')),
                ('vision', models.FileField(blank=True, upload_to='media/medicalrecords/specificexams', verbose_name='Vision Exam')),
                ('ear', models.FileField(blank=True, upload_to='media/medicalrecords/specificexams', verbose_name='Ear Exam')),
                ('hearth', models.FileField(blank=True, upload_to='media/medicalrecords/specificexams', verbose_name='Hearth Exam')),
                ('muscle_skeletal_system', models.FileField(blank=True, upload_to='media/medicalrecords/specificexams', verbose_name='Muscle skeletal system Exam')),
                ('nervous_system', models.FileField(blank=True, upload_to='media/medicalrecords/specificexams', verbose_name='Nervous system Exam')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.HealthTeam', verbose_name='Author')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Specific Exam',
                'verbose_name_plural': 'Specific Exams',
            },
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='weight',
            field=models.PositiveIntegerField(help_text='In grams', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Weight at birth'),
        ),
    ]
