# Generated by Django 2.0.3 on 2018-05-07 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180507_0027'),
        ('medicalrecords', '0002_auto_20180428_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(help_text='In grams', max_length=4, verbose_name='Weight at birth')),
                ('APGAR', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)])),
                ('heart_test', models.FileField(blank=True, upload_to='media/medicalrecords', verbose_name='Heart Test')),
                ('ear_test', models.FileField(blank=True, upload_to='media/medicalrecords', verbose_name='Test of the Ear')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.HealthTeam', verbose_name='Author')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Medical Record Static Data',
            },
        ),
    ]
