# Generated by Django 2.0.3 on 2018-04-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0003_auto_20180423_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='day',
            field=models.DateTimeField(help_text='Patient Care Day', verbose_name='Created at'),
        ),
    ]
