# Generated by Django 2.0.3 on 2018-05-07 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0003_staticdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticdata',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Patient', verbose_name='Patient'),
        ),
    ]
