# Generated by Django 2.0.3 on 2018-05-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0003_complaint_exam_medicine_specificexam_staticdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificexam',
            name='author',
        ),
        migrations.RemoveField(
            model_name='specificexam',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='author',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='status',
        ),
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.IntegerField(choices=[(None, 'select a category'), (0, 'Others'), (1, 'Structured Physical Exam'), (2, 'Vision Exam'), (3, 'Ear Exam'), (4, 'Hearth Exam'), (5, 'Muscle skeletal system Exam'), (6, 'Nervous system Exam')], help_text='Please, insert the category of the exam', null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='exam',
            name='observations',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Observations'),
        ),
        migrations.DeleteModel(
            name='SpecificExam',
        ),
    ]
