# Generated by Django 2.0.3 on 2018-05-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0004_auto_20180514_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.IntegerField(choices=[(None, 'Select a category...'), (0, 'Others'), (1, 'Structured Physical Exam'), (2, 'Vision Exam'), (3, 'Ear Exam'), (4, 'Hearth Exam'), (5, 'Muscle skeletal system Exam'), (6, 'Nervous system Exam')], help_text='Please, insert the category of the exam', null=True, verbose_name='Category'),
        ),
    ]
