# Generated by Django 2.0.3 on 2018-05-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0005_auto_20180515_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medicine_use_interval',
            field=models.CharField(default='', max_length=50, verbose_name='Time between uses'),
        ),
    ]
