# Generated by Django 2.0.3 on 2018-05-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0008_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='priority_general_practitioner',
            field=models.IntegerField(choices=[(5, 'Not urgent'), (4, 'Not very urgent'), (3, 'Urgent'), (2, 'Very urgent'), (1, 'Emerging')], help_text='Please, insert the degree of general practitioner priority of the patient', verbose_name='General Practitioner Priority'),
        ),
    ]
