# Generated by Django 2.0.3 on 2018-05-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0008_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='file',
            field=models.FileField(help_text='Exam file', upload_to='media/medicalrecords/exams', verbose_name='Exam'),
        ),
    ]
