# Generated by Django 2.0.3 on 2018-05-28 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0009_auto_20180526_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticdata',
            name='foot_test',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/medicalrecords', verbose_name='Foot test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.IntegerField(choices=[(None, 'Select a category...'), (0, 'Others'), (1, 'Structured Physical Exam'), (2, 'Vision Exam'), (3, 'Ear Exam'), (4, 'Hearth Exam'), (5, 'Muscle skeletal system Exam'), (6, 'Nervous system Exam'), (7, 'Blood Exam'), (8, 'Bone Densitometry'), (9, 'Biopsy'), (10, 'Endoscopy'), (11, 'Echocardiogram'), (12, 'Map and Holter'), (13, 'Bioimpedance'), (14, 'Neurological examinations')], help_text='Please, insert the category of the exam', null=True, verbose_name='Category'),
        ),
    ]
