# Generated by Django 2.0.3 on 2018-05-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecords', '0009_auto_20180521_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='priority_cardiology',
            field=models.IntegerField(choices=[(5, 'Not urgent'), (4, 'Not very urgent'), (3, 'Urgent'), (2, 'Very urgent'), (1, 'Emerging')], default=5, help_text='Please, insert the degree of cardiology priority of the patient', verbose_name='Cardiology Priority'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='priority_general_practitioner',
            field=models.IntegerField(choices=[(5, 'Not urgent'), (4, 'Not very urgent'), (3, 'Urgent'), (2, 'Very urgent'), (1, 'Emerging')], default=5, help_text='Please, insert the degree of general practitioner priority of the patient', verbose_name='General Practitioner Priority'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='priority_neurology',
            field=models.IntegerField(choices=[(5, 'Not urgent'), (4, 'Not very urgent'), (3, 'Urgent'), (2, 'Very urgent'), (1, 'Emerging')], default=5, help_text='Please, insert the degree of neurology priority of the patient', verbose_name='Neurology Priority'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='priority_pediatrics',
            field=models.IntegerField(choices=[(5, 'Not urgent'), (4, 'Not very urgent'), (3, 'Urgent'), (2, 'Very urgent'), (1, 'Emerging')], default=5, help_text='Please, insert the degree of pediatrics priority of the patient', verbose_name='Pediatrics Priority'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='priority_physiotherapy',
            field=models.IntegerField(choices=[(5, 'Not urgent'), (4, 'Not very urgent'), (3, 'Urgent'), (2, 'Very urgent'), (1, 'Emerging')], default=5, help_text='Please, insert the degree of physiotherapy priority of the patient', verbose_name='Physiotherapy Priority'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='priority_psychology',
            field=models.IntegerField(choices=[(5, 'Not urgent'), (4, 'Not very urgent'), (3, 'Urgent'), (2, 'Very urgent'), (1, 'Emerging')], default=5, help_text='Please, insert the degree of psychology priority of the patient', verbose_name='Psychology Priority'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='priority_speech_theraphy',
            field=models.IntegerField(choices=[(5, 'Not urgent'), (4, 'Not very urgent'), (3, 'Urgent'), (2, 'Very urgent'), (1, 'Emerging')], default=5, help_text='Please, insert the degree of speech therapy priority of the patient', verbose_name='Speech Therapy Priority'),
        ),
    ]
