# Generated by Django 2.0.3 on 2018-06-01 21:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20180530_2027'),
        ('medicalrecords', '0009_auto_20180528_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='Weight in kg', verbose_name='Weight')),
                ('height', models.IntegerField(help_text='Height in cm', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Height')),
                ('cephalic_perimeter', models.FloatField(help_text='Perimeter in cm', verbose_name='Cephalic Perimeter')),
                ('bmi', models.FloatField(default=0.0, verbose_name='BMI')),
                ('age', models.IntegerField(help_text='Age in months', verbose_name='Age')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Patient', verbose_name='Patient')),
            ],
        ),
    ]
