# Generated by Django 2.0.3 on 2018-06-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20180530_2027'),
        ('medicalrecords', '0010_curves'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curves',
            unique_together={('patient', 'age')},
        ),
    ]
