"""
Django settings for drdown project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

# Imports are being used indirectly, do not remove.
from .config.apps import PRODUCTION_APPS, DEVELOPMENT_APPS
from .config.database import DATABASES
from .config.password import AUTH_PASSWORD_VALIDATORS
from .config.middleware import MIDDLEWARE
from .config.templates import TEMPLATES
from .config.security import SECRET_KEY
from .config.messages import MESSAGE_TAGS
from .config.files import (
    STATIC_ROOT, MEDIA_ROOT, STATIC_URL, MEDIA_URL
)
from .config.i18n import (
    LANGUAGE_CODE, TIME_ZONE, USE_I18N, USE_L10N, USE_TZ
)
import os

# development or production enviroment
MODE_ENVIROMENT = os.getenv("MODE_ENVIROMENT", "development")

# Urls
ROOT_URLCONF = 'drdown.urls'

# WSGI - Python dotted path to the WSGI application used by Django's runserver.
WSGI_APPLICATION = 'drdown.wsgi.application'

# Allow all host/domain to access this aplication
ALLOWED_HOSTS = ['*']

# Permissions
# ROLEPERMISSIONS_MODULE = 'core.roles'

# Enviroments mode (development or production)
if MODE_ENVIROMENT == 'development':
    DEBUG = True
    INSTALLED_APPS = DEVELOPMENT_APPS

elif MODE_ENVIROMENT == 'production':
    DEBUG = False
    INSTALLED_APPS = PRODUCTION_APPS
