# Generated by Django 2.0.3 on 2018-05-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of event', max_length=50, verbose_name='Date')),
                ('time', models.TimeField(help_text='Time of event', max_length=50, verbose_name='Time')),
                ('description', models.TextField(blank=True, help_text='Description from event', max_length=500, verbose_name='Description')),
                ('organize_by', models.CharField(help_text='Person who organize the event', max_length=80, verbose_name='Organize by')),
                ('value', models.DecimalField(decimal_places=2, help_text='Event value if that is paid', max_digits=3, verbose_name='Value of event')),
            ],
        ),
    ]
