# Generated by Django 2.0.3 on 2018-05-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='events',
            name='name',
            field=models.CharField(default='', help_text='Name of event', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='events',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Event value if that is paid', max_digits=4, verbose_name='Value of event'),
        ),
    ]
