# Generated by Django 2.0.3 on 2018-05-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180528_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.CharField(default='', help_text='Location of event', max_length=50, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='events',
            name='value',
            field=models.FloatField(help_text='Event value if that is paid', verbose_name='Value of event'),
        ),
    ]
