# Generated by Django 2.0.3 on 2018-04-06 16:40

from django.db import migrations, models
import drdown.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='cpf',
            field=models.CharField(help_text='Please, use enter a valid CPF in the following format:XXX.XXX.XXX-XX', max_length=14, unique=True, validators=[drdown.utils.validators.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='crm',
            field=models.CharField(help_text='Use enter a valid CRM. \nAll digits must contain numbers from 1 to 5', max_length=7, validators=[drdown.utils.validators.validate_crm]),
        ),
    ]
