# Generated by Django 2.0.3 on 2018-04-06 18:32

from django.db import migrations, models
import drdown.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180406_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='crm',
            field=models.CharField(help_text='Use enter a valid CRM. \nAll digits must contain numbers from 0 to 9', max_length=7, validators=[drdown.utils.validators.validate_crm]),
        ),
    ]
