# Generated by Django 2.0.3 on 2018-04-07 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drdown.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180325_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(help_text='Please, use enter a valid CPF in the following format:XXX.XXX.XXX-XX', max_length=14, unique=True, validators=[drdown.utils.validators.validate_cpf])),
                ('crm', models.CharField(help_text='Use enter a valid CRM. \nAll digits must contain numbers from 0 to 9', max_length=7, validators=[drdown.utils.validators.validate_crm])),
                ('speciality', models.CharField(blank=True, choices=[('Speech Therapy', 'Speech Therapy'), ('Occupational Therapy', 'Occupational Therapy'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('Psychology', 'Psychology'), ('Physiotherapy', 'Physiotherapy')], help_text='The speciality that this doctor works.', max_length=30)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(help_text='Please, enter a valid CPF in the following format: XXX.XXX.XXX-XX', max_length=14, unique=True, validators=[drdown.utils.validators.validate_cpf])),
                ('departament', models.CharField(choices=[('SP_TH', 'Speech Therapy'), ('OC_TH', 'Occupational Therapy'), ('CARD', 'Cardiology'), ('NEURO', 'Neurology'), ('PED', 'Pediatrics'), ('PSY', 'Psychology'), ('PHYS', 'Physiotherapy'), ('SEC', 'Secretary'), ('ADM', 'Administration'), ('NUR', 'Nursery'), ('OTH', 'Other')], help_text='The departament where this user works.', max_length=30)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ses', models.CharField(help_text='Please, enter the valid SES number', max_length=9, unique=True, validators=[drdown.utils.validators.validate_ses])),
                ('priority', models.IntegerField(choices=[(5, 'Not urgent'), (4, 'Not very urgent'), (3, 'Urgent'), (2, 'Very urgent'), (1, 'Emerging')], help_text='Please, insert the degree of priority of the patient')),
                ('mother_name', models.CharField(help_text='Please, insert your mother name', max_length=80, validators=[drdown.utils.validators.validate_names])),
                ('father_name', models.CharField(help_text='Please, insert your father name', max_length=80, validators=[drdown.utils.validators.validate_names])),
                ('ethnicity', models.IntegerField(choices=[(5, 'White'), (4, 'Black'), (3, 'Yellow'), (2, 'Brown'), (1, 'Indigenous')], help_text='Please insert the ethnicity of the patient')),
                ('sus_number', models.CharField(help_text='Please, enter valid SUS in format: XXXXXXXXXXXXXXX', max_length=15, unique=True, validators=[drdown.utils.validators.validate_sus])),
                ('civil_registry_of_birth', models.CharField(default='', help_text='Please, enter the civil registry of birth number', max_length=11, unique=True, validators=[drdown.utils.validators.validate_generic_number])),
                ('declaration_of_live_birth', models.CharField(default='', help_text='Please, enter the declaration of live birth number', max_length=11, unique=True, validators=[drdown.utils.validators.validate_generic_number])),
            ],
        ),
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(help_text='Please, use enter a valid CPF inthe following format: XXX.XXX.XXX-XX', max_length=14, unique=True, validators=[drdown.utils.validators.validate_cpf])),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateField(null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo of user.', null=True, upload_to='media/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateField(null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(help_text='xx/xx/xxxx', null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Full user name', max_length=255, verbose_name='Name of User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(help_text='(xx)xxxxx-xxxx or (xx)xxxx-xxxx', max_length=14, null=True, validators=[drdown.utils.validators.validate_phone], verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='responsible',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
