# Generated by Django 2.0.3 on 2018-04-03 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drdown.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180325_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(help_text='Please, use enter a valid CPF in the following format: XXX.XXX.XXX-XX', max_length=15, unique=True, validators=[drdown.utils.validators.validate_cpf])),
                ('departament', models.CharField(help_text='The departament where this user works.', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telephone',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
