# Generated by Django 2.0.3 on 2018-04-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180404_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='departament',
            field=models.CharField(choices=[('SP_TH', 'Speech Therapy'), ('OC_TH', 'Occupational Therapy'), ('CARD', 'Cardiology'), ('NEURO', 'Neurology'), ('PED', 'Pediatrics'), ('PSY', 'Psychology'), ('PHYS', 'Physiotherapy'), ('SEC', 'Secretary'), ('OTH', 'Other')], help_text='The departament where this user works.', max_length=30),
        ),
    ]
