# Generated by Django 2.0.3 on 2018-04-13 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drdown.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180407_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsible',
            name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Responsible'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_specialization',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='crm',
            field=models.CharField(help_text='Use enter a valid CRM. \nEnter 7 digits from 0 to 9', max_length=7, validators=[drdown.utils.validators.validate_crm]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(blank=True, choices=[('Speech Therapy', 'Speech Therapy'), ('Occupational Therapy', 'Occupational Therapy'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('Psychology', 'Psychology'), ('Physiotherapy', 'Physiotherapy')], help_text='The speciality that this doctor works.', max_length=30, verbose_name='Speciality'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(limit_choices_to=models.Q(has_specialization=False), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='departament',
            field=models.CharField(choices=[('SP_TH', 'Speech Therapy'), ('OC_TH', 'Occupational Therapy'), ('CARD', 'Cardiology'), ('NEURO', 'Neurology'), ('PED', 'Pediatrics'), ('PSY', 'Psychology'), ('PHYS', 'Physiotherapy'), ('SEC', 'Secretary'), ('ADM', 'Administration'), ('NUR', 'Nursery'), ('OTH', 'Other')], help_text='The departament where this user works.', max_length=30, verbose_name='Departament'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(limit_choices_to=models.Q(has_specialization=False), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='civil_registry_of_birth',
            field=models.CharField(default='', help_text='Please, enter the civil registry of birth number', max_length=11, unique=True, validators=[drdown.utils.validators.validate_generic_number], verbose_name='Civil register of birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='declaration_of_live_birth',
            field=models.CharField(default='', help_text='Please, enter the declaration of live birth number', max_length=11, unique=True, validators=[drdown.utils.validators.validate_generic_number], verbose_name='Declaration of live birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ethnicity',
            field=models.IntegerField(choices=[(5, 'White'), (4, 'Black'), (3, 'Yellow'), (2, 'Brown'), (1, 'Indigenous')], help_text='Please insert the ethnicity of the patient', verbose_name='Ethnicity'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='father_name',
            field=models.CharField(help_text='Please, insert your father name', max_length=80, validators=[drdown.utils.validators.validate_names], verbose_name='Name of father'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='priority',
            field=models.IntegerField(choices=[(5, 'Not urgent'), (4, 'Not very urgent'), (3, 'Urgent'), (2, 'Very urgent'), (1, 'Emerging')], help_text='Please, insert the degree of priority of the patient', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sus_number',
            field=models.CharField(help_text='Please, enter valid SUS in format: XXXXXXXXXXXXXXX', max_length=15, unique=True, validators=[drdown.utils.validators.validate_sus], verbose_name='SUS number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(limit_choices_to=models.Q(has_specialization=False), on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='user',
            field=models.OneToOneField(limit_choices_to=models.Q(has_specialization=False), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Full user name', max_length=255, verbose_name='Name'),
        ),
    ]
