# Generated by Django 2.0.3 on 2018-04-11 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drdown.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180407_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsible',
            name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Responsible'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='crm',
            field=models.CharField(help_text='Use enter a valid CRM. \nEnter 7 digits from 0 to 9', max_length=7, validators=[drdown.utils.validators.validate_crm]),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='user',
            field=models.OneToOneField(limit_choices_to=models.Q(patient=None), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
