# Generated by Django 2.0.3 on 2018-04-19 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180418_0108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='health_team',
            options={'verbose_name': 'Health Team', 'verbose_name_plural': 'Health Team'},
        ),
    ]
