# Generated by Django 2.0.3 on 2018-04-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Urgency',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], default=0, help_text='Please, insert the degree of urgency of the patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='SES',
            field=models.CharField(help_text='Please, enter the valid SES', max_length=9, unique=True),
        ),
    ]
