# Generated by Django 2.0.3 on 2018-04-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180417_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='departament',
            field=models.CharField(choices=[('SEC', 'Secretary'), ('ADM', 'Administration'), ('NUR', 'Nursery'), ('OTH', 'Other')], help_text='The departament where this user works.', max_length=30, verbose_name='Departament'),
        ),
    ]
