# Generated by Django 2.0.3 on 2018-04-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180404_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateField(blank=True, null=True, verbose_name='Updated at'),
        ),
    ]
