# Generated by Django 2.0.3 on 2018-04-16 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drdown.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180416_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(help_text='Please, use enter a valid CPF in the following format:XXX.XXX.XXX-XX', max_length=14, unique=True, validators=[drdown.utils.validators.validate_cpf])),
                ('crm', models.CharField(help_text='Use enter a valid CRM. \nEnter 7 digits from 0 to 9', max_length=7, validators=[drdown.utils.validators.validate_crm])),
                ('speciality', models.CharField(blank=True, choices=[('Speech Therapy', 'Speech Therapy'), ('Occupational Therapy', 'Occupational Therapy'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('Psychology', 'Psychology'), ('Physiotherapy', 'Physiotherapy'), ('Doctor', 'Doctor')], help_text='The speciality that this member of health team works.', max_length=30, verbose_name='Speciality')),
                ('user', models.OneToOneField(limit_choices_to=models.Q(has_specialization=False), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HealthTeam',
                'verbose_name_plural': 'HealthTeams',
            },
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
