# Generated by Django 2.0.3 on 2018-04-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180416_1925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HealthTeam',
            new_name='Health_Team',
        ),
        migrations.AlterModelOptions(
            name='health_team',
            options={'verbose_name': 'Health_Team', 'verbose_name_plural': 'Health_Teams'},
        ),
    ]
