# Generated by Django 2.0.3 on 2018-04-19 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180415_1311'),
        ('users', '0009_auto_20180418_1936'),
    ]

    operations = [
    ]
