# Generated by Django 2.0.3 on 2018-04-04 18:44

from django.db import migrations, models
import drdown.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180404_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Priority',
            new_name='priority',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='SES',
        ),
        migrations.AddField(
            model_name='patient',
            name='ses',
            field=models.CharField(default='', help_text='Please, enter the valid SES', max_length=9, unique=True, validators=[drdown.utils.validators.validate_ses]),
            preserve_default=False,
        ),
    ]
