# Generated by Django 2.0.3 on 2018-04-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(help_text='xx/xx/xxxx', null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Full user name', max_length=255, verbose_name='Name of User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(help_text='(xx)xxxxx-xxxx', max_length=14, null=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateField(null=True, verbose_name='Updated at'),
        ),
    ]
