# Generated by Django 2.0.3 on 2018-04-16 21:54

from django.db import migrations, models
import drdown.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180416_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health_team',
            name='crm',
        ),
        migrations.AddField(
            model_name='health_team',
            name='register_number',
            field=models.CharField(default='', help_text='Use enter a valid CRM. \nEnter 7 digits', max_length=7, validators=[drdown.utils.validators.validate_crm]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health_team',
            name='state_register',
            field=models.CharField(blank=True, choices=[(('Acre',), 'Acre'), (('Alagoas',), 'Alagoas'), (('Amapá',), 'Amapá'), (('Bahia',), 'Bahia'), (('Ceará',), 'Ceará'), (('Distrito Federal',), 'Distrito Federal'), (('Espírito Santo',), 'Espírito Santo'), (('Goiás',), 'Goiás'), (('Maranhão',), 'Maranão'), (('Minas Gerais',), 'Minas Gerais'), (('Mato Grosso do Sul',), 'Mato Grosso do Sul'), (('Mato Grosso',), 'Mato Grosso'), (('Pará',), 'Pará'), (('Paraíba',), 'Paraíba'), (('Pernanbuco',), 'Pernanbuco'), (('Piauí',), 'Piauí'), (('Paraná',), 'Paraná'), (('Rio de Janeiro',), 'Rio de Janeiro'), (('Rio Grande do Norte',), 'Rio Grande do Norte'), (('Rondônia',), 'Rondônia'), (('Roraima',), 'Roraima'), (('Rio Grande do Sul',), 'Rio Grande do Sul'), (('Santa Catarina',), 'Santa Catarina'), (('Sergipe',), 'Sergipe'), (('São Paulo',), 'São Paulo'), ('Tocantins', 'Tocantins')], help_text='The speciality that this member of health team works.', max_length=30, verbose_name='Speciality'),
        ),
    ]
