# Generated by Django 2.0.3 on 2018-04-06 11:47

from django.db import migrations, models
import drdown.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180405_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(help_text='(xx)xxxxx-xxxx', max_length=14, null=True, validators=[drdown.utils.validators.validate_phone], verbose_name='Telephone'),
        ),
    ]
