# Generated by Django 2.0.3 on 2018-04-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180419_0309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Health_Team',
            new_name='HealthTeam',
        ),
    ]
