# Generated by Django 2.0.3 on 2018-04-05 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsible',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Patient'),
        ),
        migrations.AlterUniqueTogether(
            name='responsible',
            unique_together={('user', 'patient')},
        ),
    ]
