# Generated by Django 2.0.3 on 2018-04-06 14:59

from django.db import migrations, models
import drdown.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180406_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo of user.', null=True, upload_to='drdown/static/images/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(help_text='(xx)xxxxx-xxxx or (xx)xxxx-xxxx', max_length=14, null=True, validators=[drdown.utils.validators.validate_phone], verbose_name='Telephone'),
        ),
    ]
