# Generated by Django 2.0.3 on 2018-04-24 01:25

from django.db import migrations, models
import drdown.users.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180423_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthteam',
            name='council_acronym',
            field=models.CharField(choices=[('CRM', 'CRM'), ('CRP', 'CRP'), ('CREFITO', 'CREFITO'), ('COREN', 'COREN'), ('CREFONO', 'CREFONO')], help_text='The Regional Council.', max_length=30, verbose_name='Council Acronym'),
        ),
        migrations.AlterField(
            model_name='healthteam',
            name='register_number',
            field=models.CharField(help_text='Use enter a valid register number.', max_length=9, validators=[drdown.users.utils.validators.validate_register_number]),
        ),
        migrations.AlterField(
            model_name='healthteam',
            name='speciality',
            field=models.CharField(choices=[('Speech Therapy', 'Speech Therapy'), ('Psychology', 'Psychology'), ('Physiotherapy', 'Physiotherapy'), ('Occupational Therapy', 'Occupational Therapy'), ('Doctor', 'Doctor'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('Nursing', 'Nursing')], help_text='The speciality that this member of health team works.', max_length=30, verbose_name='Speciality'),
        ),
    ]
