# Generated by Django 2.0.3 on 2018-04-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180405_1654'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='responsible',
            unique_together=set(),
        ),
    ]
