# Generated by Django 2.0.3 on 2018-04-05 23:41

from django.db import migrations, models
import drdown.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180405_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='civil_registry_of_birth',
            field=models.CharField(default='', help_text='Please, enter the civil registry of birth number', max_length=11, unique=True, validators=[drdown.utils.validators.validate_generic_number]),
        ),
        migrations.AddField(
            model_name='patient',
            name='declaration_of_live_birth',
            field=models.CharField(default='', help_text='Please, enter the declaration of live birth number', max_length=11, unique=True, validators=[drdown.utils.validators.validate_generic_number]),
        ),
        migrations.AddField(
            model_name='patient',
            name='ethnicity',
            field=models.IntegerField(choices=[(5, 'White'), (4, 'Black'), (3, 'Yellow'), (2, 'Brown'), (1, 'Indigenous')], default=0, help_text='Please insert the ethnicity of the patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='father_name',
            field=models.CharField(default='', help_text='Please, insert your father name', max_length=80, validators=[drdown.utils.validators.validate_names]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='mother_name',
            field=models.CharField(default='', help_text='Please, insert your mother name', max_length=80, validators=[drdown.utils.validators.validate_names]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='sus_number',
            field=models.CharField(default='', help_text='Please, enter the valid SUS number', max_length=11, unique=True, validators=[drdown.utils.validators.validate_generic_number]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='priority',
            field=models.IntegerField(choices=[(5, 'Not urgent'), (4, 'Not very urgent'), (3, 'Urgent'), (2, 'Very urgent'), (1, 'Emerging')], help_text='Please, insert the degree of priority of the patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ses',
            field=models.CharField(help_text='Please, enter the valid SES number', max_length=9, unique=True, validators=[drdown.utils.validators.validate_ses]),
        ),
    ]
