# Generated by Django 2.0.3 on 2018-04-16 22:50

from django.db import migrations, models
import drdown.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180416_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_team',
            name='council_acronym',
            field=models.CharField(blank=True, choices=[('CRM', 'CRM'), ('CRP', 'CRP'), ('COFFITO', 'COFFITO')], help_text='The speciality that this member of health team works.', max_length=30, verbose_name='Council Acronym'),
        ),
        migrations.AlterField(
            model_name='health_team',
            name='register_number',
            field=models.CharField(help_text='Use enter a valid register number. \nEnter 7 digits', max_length=7, validators=[drdown.utils.validators.validate_crm]),
        ),
        migrations.AlterField(
            model_name='health_team',
            name='state_register',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], help_text='The state of register health team member works.', max_length=30, verbose_name='State'),
        ),
    ]
