# Generated by Django 2.0.3 on 2018-04-24 20:32

from django.db import migrations, models
import drdown.users.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180424_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthteam',
            name='register_number',
            field=models.CharField(help_text='Enter a valid register number.', max_length=9, validators=[drdown.users.utils.validators.validate_register_number], verbose_name='Register Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True, verbose_name='Gender'),
        ),
    ]
