# Generated by Django 2.0.3 on 2018-04-06 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drdown.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180405_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sus_number',
            field=models.CharField(help_text='Please, enter the valid SUS number', max_length=15, unique=True, validators=[drdown.utils.validators.validate_sus]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
