# Generated by Django 2.0.3 on 2018-04-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180424_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
    ]
