# Generated by Django 2.0.3 on 2018-04-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180406_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo of user.', null=True, upload_to='media/', verbose_name='Photo'),
        ),
    ]
