# Generated by Django 2.0.3 on 2018-04-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180416_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_team',
            name='registration_state',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], help_text='The registration state of member of health team.', max_length=30, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='health_team',
            name='council_acronym',
            field=models.CharField(blank=True, choices=[('CRM', 'CRM'), ('CRP', 'CRP'), ('COFFITO', 'COFFITO')], help_text='The Regional Council.', max_length=30, verbose_name='Council Acronym'),
        ),
        migrations.RemoveField(
            model_name='health_team',
            name='state_register',
        ),
        migrations.AlterUniqueTogether(
            name='health_team',
            unique_together={('registration_state', 'register_number', 'council_acronym')},
        ),
    ]
