# Generated by Django 2.0.3 on 2018-04-06 18:38

from django.db import migrations, models
import drdown.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180406_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sus_number',
            field=models.CharField(help_text='Please, use enter a valid SUS in the following format: XXXXXXXXXXXXXXX', max_length=15, unique=True, validators=[drdown.utils.validators.validate_sus]),
        ),
    ]
