# Generated by Django 2.0.3 on 2018-04-06 20:11

from django.db import migrations, models
import drdown.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180406_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sus_number',
            field=models.CharField(help_text='Please, enter valid SUS in format: XXXXXXXXXXXXXXX', max_length=15, unique=True, validators=[drdown.utils.validators.validate_sus]),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='cpf',
            field=models.CharField(help_text='Please, use enter a valid CPF inthe following format: XXX.XXX.XXX-XX', max_length=14, unique=True, validators=[drdown.utils.validators.validate_cpf]),
        ),
    ]
