# Generated by Django 2.0.3 on 2018-05-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180506_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='priority',
        ),
    ]
