# Generated by Django 2.0.3 on 2018-06-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20180530_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='departament',
            field=models.CharField(choices=[('SEC', 'Secretary'), ('ADM', 'Administration'), ('OTH', 'Other')], help_text='The departament where this user works.', max_length=30, verbose_name='Departament'),
        ),
    ]
